language: ruby
bundler_args: --jobs 4 --retry 3 --without development
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - psql -c 'create database myapp_test;' -U postgres
  - "cp config/database.travis.yml config/database.yml"
  - phantomjs --version
script: RSPEC_EXCLUDE_UNSTABLE=1 ./script/cibuild.sh
rvm:
  - 2.1.0
sudo: false
