language: elixir
elixir: '1.10.3'
otp_release: '22.3'
before_install: gem install sass
script: cd assets && npm install && node_modules/webpack/bin/webpack.js --mode development && cd .. && mix test
services:
  - postgresql
  - redis-server
env:
  - REDIS_URL=redis://localhost:6379
cache:
  directories:
    - assets/node_modules
    - deps
    - _build
